{
  "swagger": "2.0",
  "info": {
    "title": "Studies API",
    "version": "1.0",
    "description": "Api реестра исследований",
    "contact": {
      "name": "Oleg Ovcharenko",
      "email": "oleg.ovcharenko@labworks.ru"
    },
    "license": {
      "name": "Apache 2.0"
    }
  },
  "paths": {
    "/catalogs/studies": {
      "get": {
        "operationId": "findStudies",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/study-output"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": "ipsum cillum",
                  "name": "occaecat eiusmod ex",
                  "enabled": true,
                  "dateCreated": "1945-11-21T14:30:32.642Z",
                  "dateUpdated": "1939-09-26T04:54:11.370Z"
                },
                {
                  "id": "qui elit",
                  "name": "non consequ",
                  "enabled": false,
                  "dateCreated": "1982-10-10T08:27:10.549Z",
                  "dateUpdated": "1969-07-04T01:52:52.192Z"
                },
                {
                  "id": "in ipsum anim",
                  "name": "veniam nostrud nisi voluptate magna",
                  "enabled": false,
                  "dateCreated": "1979-11-21T03:48:10.831Z",
                  "dateUpdated": "1946-02-04T03:21:49.296Z"
                },
                {
                  "id": "Ut nulla minim",
                  "name": "eu pariatur",
                  "enabled": true,
                  "dateCreated": "1944-02-08T06:55:06.810Z",
                  "dateUpdated": "1983-12-16T08:24:57.184Z"
                }
              ]
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          }
        },
        "parameters": [
          {
            "in": "query",
            "name": "enabled",
            "type": "boolean",
            "description": "Переключатель активные/неактивные"
          },
          {
            "in": "query",
            "name": "year",
            "type": "integer",
            "format": "int32",
            "description": "Год создания исследования",
            "minimum": 2016,
            "maximum": 2050
          }
        ],
        "summary": "Получить список исследований.",
        "description": "По умолчанию все исследования.\nЕсли имеется параметр enabled, то true - активные, false - неактивные"
      },
      "post": {
        "operationId": "createStudy",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/study-input"
            },
            "x-examples": {
              "application/json": {
                "name": "do in e",
                "enabled": false
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/study-output-detailed"
            },
            "examples": {
              "application/json": {
                "id": "a1b2c3d4e5f678",
                "name": "dolore tempor nulla laboris",
                "enabled": true,
                "dateCreated": "1957-06-10T21:31:33.691Z",
                "dateUpdated": ""
              }
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          },
          "422": {
            "$ref": "../errors.json#/responses/422"
          }
        },
        "summary": "Создать новое исследование"
      }
    },
    "/catalogs/studies/{studyId}": {
      "parameters": [
        {
          "name": "studyId",
          "in": "path",
          "type": "string",
          "required": true
        }
      ],
      "get": {
        "operationId": "getStudy",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/study-output-detailed"
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          },
          "404": {
            "$ref": "../errors.json#/responses/404"
          }
        },
        "summary": "Получить исследование по ID"
      },
      "put": {
        "operationId": "updateStudy",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/study-input"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/study-output-detailed"
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          },
          "404": {
            "$ref": "../errors.json#/responses/404"
          }
        },
        "summary": "Изменить исследование"
      },
      "delete": {
        "operationId": "deleteStudy",
        "responses": {
          "200": {
            "description": "Документ успешно удален",
            "schema": {
              "$ref": "#/definitions/study-output-detailed"
            },
            "examples": {
              "application/json": {
                "id": "da1b2c3d4e5f678",
                "name": "proident",
                "enabled": true,
                "dateCreated": "1958-05-17T04:27:56.853Z",
                "dateUpdated": "1940-12-11T17:52:41.182Z"
              }
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          },
          "404": {
            "$ref": "../errors.json#/responses/404"
          }
        },
        "summary": "Удалить исследование",
        "description": "Удалить исследование с идентификатором studyId"
      }
    },
    "/catalogs/studies/upload": {
      "post": {
        "x-hapi-options": {
          "payload": {
            "maxBytes": 123456789,
            "output": "data",
            "parse": true
          }
        },
        "responses": {
          "200": {
            "description": "Файл успешно загружен",
            "schema": {
              "$ref": "#/definitions/study-file-output"
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          }
        },
        "summary": "Загрузка файлов исследования",
        "operationId": "uploadStudyFile",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "in": "formData",
            "name": "upFile",
            "type": "file",
            "required": true
          },
          {
            "in": "formData",
            "name": "studyId",
            "type": "string",
            "required": true
          },
          {
            "in": "formData",
            "name": "fileName",
            "type": "string",
            "required": true
          },
          {
            "in": "formData",
            "name": "fileType",
            "type": "string",
            "required": true
          }
        ]
      }
    }
  },
  "host": "localhost:3000",
  "basePath": "/api",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "definitions": {
    "study-common": {
      "title": "Study",
      "description": "Исследование",
      "type": "object",
      "properties": {
        "studyNo": {
          "type": "string",
          "description": "Код исследования"
        },
        "planYear": {
          "type": "number",
          "minimum": 2015,
          "maximum": 2050,
          "description": "Планируемый год"
        },
        "customerId": {
          "type": "string",
          "description": "Заказчик"
        },
        "test_objectId": {
          "type": "string",
          "description": "Тестируемый объект"
        },
        "enabled": {
          "type": "boolean",
          "description": "Признак активности"
        }
      },
      "required": [
        "studyNo",
        "planYear",
        "customerId",
        "test_objectId",
        "enabled"
      ]
    },
    "study-input": {
      "title": "Study Input",
      "description": "The properties that are allowed when creating or updating a Study.",
      "allOf": [
        {
          "$ref": "#/definitions/study-common"
        },
        {
          "type": "object",
          "properties": {}
        }
      ]
    },
    "study-output": {
      "title": "Study Basic Output",
      "description": "The properties that are included when fetching a list of Studies.",
      "allOf": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Идентификатор"
            },
            "serialNumber": {
              "type": "number",
              "description": "Порядковый номер исследования",
              "minimum": 1,
              "maximum": 100
            }
          },
          "required": [
            "id",
            "serialNumber"
          ]
        },
        {
          "$ref": "#/definitions/study-common"
        },
        {
          "type": "object",
          "properties": {
            "dateCreated": {
              "type": "string",
              "format": "date-time",
              "description": "Дата создания"
            },
            "dateUpdated": {
              "type": "string",
              "format": "date-time",
              "description": "Дата последнего редактирования"
            }
          },
          "required": [
            "dateCreated",
            "dateUpdated"
          ]
        }
      ]
    },
    "study-output-detailed": {
      "title": "Study Detailed Output",
      "description": "The properties that are included when fetching a single Study.",
      "allOf": [
        {
          "$ref": "#/definitions/study-output"
        },
        {
          "type": "object",
          "properties": {}
        }
      ]
    },
    "study-file-output": {
      "type": "object",
      "title": "Study Upload File Output",
      "required": [
        "studyId"
      ],
      "properties": {
        "studyId": {
          "type": "string"
        }
      }
    }
  }
}