{
  "swagger": "2.0",
  "info": {
    "title": "Customers API",
    "version": "1.0",
    "description": "Api справочника Заказчики",
    "contact": {
      "name": "Oleg Ovcharenko",
      "email": "oleg.ovcharenko@labworks.ru"
    },
    "license": {
      "name": "Apache 2.0"
    }
  },
  "paths": {
    "/dir/customers": {
      "get": {
        "operationId": "findCustomers",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/customer-output"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": "ipsum cillum",
                  "name": "occaecat eiusmod ex",
                  "enabled": true,
                  "dateCreated": "1945-11-21T14:30:32.642Z",
                  "dateUpdated": "1939-09-26T04:54:11.370Z"
                },
                {
                  "id": "qui elit",
                  "name": "non consequ",
                  "enabled": false,
                  "dateCreated": "1982-10-10T08:27:10.549Z",
                  "dateUpdated": "1969-07-04T01:52:52.192Z"
                },
                {
                  "id": "in ipsum anim",
                  "name": "veniam nostrud nisi voluptate magna",
                  "enabled": false,
                  "dateCreated": "1979-11-21T03:48:10.831Z",
                  "dateUpdated": "1946-02-04T03:21:49.296Z"
                },
                {
                  "id": "Ut nulla minim",
                  "name": "eu pariatur",
                  "enabled": true,
                  "dateCreated": "1944-02-08T06:55:06.810Z",
                  "dateUpdated": "1983-12-16T08:24:57.184Z"
                }
              ]
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          }
        },
        "parameters": [
          {
            "in": "query",
            "name": "enabled",
            "type": "boolean",
            "description": "Переключатель активные/неактивные"
          },
          {
            "in": "query",
            "name": "short",
            "type": "boolean",
            "description": "краткий/полный ответ"
          }
        ],
        "summary": "Получить список заказчиков исследований.",
        "description": "По умолчанию все заказчики.\nЕсли имеется параметр enabled, то true - активные, false - неактивные"
      },
      "post": {
        "operationId": "createCustomer",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/customer-input"
            },
            "x-examples": {
              "application/json": {
                "name": "do in e",
                "enabled": false
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customer-output-detailed"
            },
            "examples": {
              "application/json": {
                "id": "a1b2c3d4e5f678",
                "name": "dolore tempor nulla laboris",
                "enabled": true,
                "dateCreated": "1957-06-10T21:31:33.691Z",
                "dateUpdated": ""
              }
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          },
          "422": {
            "$ref": "../errors.json#/responses/422"
          }
        },
        "summary": "Создать нового заказчика"
      }
    },
    "/dir/customers/{customerId}": {
      "parameters": [
        {
          "name": "customerId",
          "in": "path",
          "type": "string",
          "required": true
        }
      ],
      "get": {
        "operationId": "getCustomer",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customer-output-detailed"
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          },
          "404": {
            "$ref": "../errors.json#/responses/404"
          }
        },
        "summary": "Получить заказчика по ID"
      },
      "put": {
        "operationId": "updateCustomer",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/customer-input"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/customer-output-detailed"
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          },
          "404": {
            "$ref": "../errors.json#/responses/404"
          }
        },
        "summary": "Изменить заказчика"
      },
      "delete": {
        "operationId": "deleteCustomer",
        "responses": {
          "200": {
            "description": "Документ успешно удален",
            "schema": {
              "$ref": "#/definitions/customer-output-detailed"
            },
            "examples": {
              "application/json": {
                "id": "da1b2c3d4e5f678",
                "name": "proident",
                "enabled": true,
                "dateCreated": "1958-05-17T04:27:56.853Z",
                "dateUpdated": "1940-12-11T17:52:41.182Z"
              }
            }
          },
          "400": {
            "$ref": "../errors.json#/responses/400"
          },
          "404": {
            "$ref": "../errors.json#/responses/404"
          }
        },
        "summary": "Удалить заказчика",
        "description": "Удалить заказчика с идентификатором customerId"
      }
    }
  },
  "host": "localhost:3000",
  "basePath": "/api",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "definitions": {
    "customer-common": {
      "title": "Customer",
      "description": "Заказчик или спонсор исследования",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Наименование заказчика"
        },
        "enabled": {
          "type": "boolean",
          "description": "Признак активности"
        }
      },
      "required": [
        "name",
        "enabled"
      ]
    },
    "customer-input": {
      "title": "Customer Input",
      "description": "The properties that are allowed when creating or updating a Customer.",
      "allOf": [
        {
          "$ref": "#/definitions/customer-common"
        },
        {
          "type": "object",
          "properties": {}
        }
      ]
    },
    "customer-output": {
      "title": "Customer Basic Output",
      "description": "The properties that are included when fetching a list of Customers.",
      "allOf": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Идентификатор"
            }
          },
          "required": [
            "id"
          ]
        },
        {
          "$ref": "#/definitions/customer-common"
        },
        {
          "type": "object",
          "properties": {
            "dateCreated": {
              "type": "string",
              "format": "date-time",
              "description": "Дата создания"
            },
            "dateUpdated": {
              "type": "string",
              "format": "date-time",
              "description": "Дата последнего редактирования"
            }
          },
          "required": [
            "dateCreated",
            "dateUpdated"
          ]
        }
      ]
    },
    "customer-output-detailed": {
      "title": "Customer Detailed Output",
      "description": "The properties that are included when fetching a single Customer.",
      "allOf": [
        {
          "$ref": "#/definitions/customer-output"
        },
        {
          "type": "object",
          "properties": {}
        }
      ]
    }
  }
}